# Generated by Django 4.1.7 on 2023-05-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=50)),
                ('desc_pro', models.CharField(max_length=250)),
                ('cat_pro', models.CharField(max_length=100)),
                ('precio_pro', models.PositiveIntegerField()),
                ('stock_pro', models.IntegerField()),
            ],
        ),
    ]
