# Generated by Django 4.1.7 on 2023-05-13 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_producto', models.PositiveIntegerField()),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('codigo_sucursal', models.IntegerField()),
                ('sub_total', models.PositiveIntegerField()),
                ('lista_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listaproductos')),
            ],
        ),
    ]
