# Generated by Django 4.1.7 on 2023-05-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listaproductos_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_producto', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='lista_productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sub_total',
        ),
        migrations.DeleteModel(
            name='ListaProductos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalle_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.detallepedido'),
        ),
    ]
