# Generated by Django 4.1.7 on 2023-05-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detallepedido_remove_pedido_lista_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle_pedido',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='codigo_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pedido'),
        ),
    ]
