# Generated by Django 4.1.7 on 2023-05-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pedido_detalle_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_pro',
            field=models.PositiveIntegerField(),
        ),
    ]
